### ISSUE TITLE
Feature Request - Include Item Quantity in Charge calculation

### ISSUE THREAD

**Issue by SoundSherpa** [ElfFriend-DnD/foundryvtt-link-item-resource-5e#2]
Possibly be able to use item count as a resource (arrows for instance) or even spell slots remaining. This mod is awesome and I dont use the resource sections otherwise since none of them sync.

**Comment by akrigline** [comment]
Thanks for this feedback!

Gonna say no on Spell Slots, but the Quantity of an Item (especially a consumable) is an interesting idea and in-line with the goal.

It would be a good extension of the existing logic around charges similar to how the core system's charges logic works.

The core system for instance allows consumables to consume quantity on-use (this is how arrows work IIRC), so that's pretty on brand with what I'm accomplishing here. The logic might be tricky when both charges and quantity are present, I'll have to look at what the core does again to make sure I mirror it.

**Comment by ravingdragoon** [comment]
Came here to make the same request myself. Glad to see it is already being looked at! :)

**Comment by akrigline** [comment]
I'm pleased to announce that this is now possible with release 1.2.0! Take a look and let me know what you think!

**Comment by ravingdragoon** [comment]
This is awesome! Thank you so much for your hard work!!!

**Comment by SoundSherpa** [comment]
> I'm pleased to announce that this is now possible with release 1.2.0! Take a look and let me know what you think!

This works for me, thanks!
